import LocalizedStrings from "react-localization";


const strings = new LocalizedStrings({
	en: {
		errorMsg: 'Some thing went wrong. Error code: {code}',
		errorRetry: 'Retrying...',
		errorRetryFail: 'Please retry later or contact the admin.',
		helperTitle: 'What\'s this?',
		helperName: 'What To Sell Today',
		helperOrigin: '{0} (mentioned as WTST below) was developed to help choosing the worthiest item for retainer ventures at the beginning. ' +
			'Now it also supports currency exchanging including timestone, timeworn maps and more.',
		helperDataOrigin: 'WTST queries data from {0} (mentioned as uni below). ' +
			'After simple calculations, WTST provides market statistics for each item and present it to user. ' +
			'Due to the mechanism of uni, the market data may not be fresh enough. ' +
			'Therefore participating in market data gathering for uni is always welcommed. ' +
			'Visit {1} to learn more about uni.',
		helperNGAOrigin: 'this NGA post',
		helperNGAURL: 'https://bbs.nga.cn/read.php?tid=22462774&rand=476',
		helperUniOrigin: 'this site',
		helperUniURL: 'https://universalis.app/about',
		helperOther: 'If something went wrong, please contact the developer. ' +
			'Google recaptcha is introduced in WTST for protection purpose.',
		barPrefix: 'What to {action} ',
		barPostfix: ' today?',
		drawerAppearance: 'Appearance',
		drawerTheme: 'Theme',
		drawerDay: 'light',
		drawerNight: 'dark',
		drawerAuto: 'auto',
		drawerAutoUpdate: 'Automatically applied',
		drawerQuality: 'Item Quality',
		drawerHQ: 'HQ',
		drawerNQ: 'NQ',
		drawerAll: 'all',
		drawerConsiderTime: 'Consider time cost?',
		drawerManualUpdate: 'Manually applied',
		drawerDC: 'Current DC',
		drawerWorld: 'Current World',
		drawerAverageWindowSize: 'Average Window Size',
		drawerUpdate: 'UPDATE',
		categoryCurrency: 'currency',
		categoryRetainer: 'retainer',
		categoryGathering: 'gathering',
		categoryCrafting: 'crafting',
		companySeal: 'Company Seals',
		companySealAction: 'exchange with ',
		botany: 'Botanist',
		botanyAction: 'gather for',
		mining: 'Miner',
		miningAction: 'gather for',
		fish: 'Fisher',
		fishAction: 'gather for ',
		hunting: ' Battlecraft',
		huntingAction: 'collect for ',
		dye: ' Dyes',
		dyeAction: 'craft among ',
		map: ' Timeworn Maps',
		mapAaction: 'dig among ',
		allegory: ' allegory',
		allegoryAction: 'exchange with ',
		yellowGathererScrips: ' Yellow Gatherer Scrips',
		yellowGathererScripsAction: 'exchange with ',
		gridItem: 'Name',
		gridLevel: 'level {0}',
		gridUpdateAt: 'Updated at',
		gridUpdateLocalAt: 'Current world',
		gridUpdateGlobalAt: 'Whole DC',
		gridCost: 'Cost',
		gridDefaultLowest: 'World min',
		gridDefaultMeanLow: 'Min average',
		gridDefaultHistLow: 'History min',
		gridDefaultHistPerCost: 'Price per Cost',
		gridLowest: 'DC min',
		gridMeanLow: 'Min average',
		gridHistLow: 'History min',
		gridHistPerCost: 'Price per Cost',
		gridVolumes: '1/3/7 days transaction',
		gridItemName: '{enName}',
		copyHint: 'Copied!'
	},
	zh: {
		errorMsg: '出错了，错误代码：{code}',
		errorRetry: '正在重试...',
		errorRetryFail: '请稍后再试，或联系管理员',
		helperTitle: '这是什么？',
		helperName: '今天带点什么',
		helperOrigin: '{0}（下称何带）最初是为了解决派雇员探险时不知道带什么的问题，现已拓展到神典石、宝图等一切本质是“资源兑换商品”的选择问题。',
		helperDataOrigin: '何带从{0}（下称uni）查询物品列表的市场信息，并进行简单的计算后提供给用户以自行选择。' +
			'因uni的数据最终来源于玩家的游戏内查询，数据更新仍会有一定延迟，因此也希望有更多人一起为uni提交数据。访问{1}了解更多uni事宜。',
		helperNGAOrigin: '此nga帖子',
		helperNGAURL: 'https://bbs.nga.cn/read.php?tid=22462774&rand=476',
		helperUniOrigin: '此处',
		helperUniURL: 'https://universalis.app/about',
		helperOther: '如何带故障无法使用，或有增加其他列表的需求，可向开发者反馈。' +
			'何带使用google recaptcha保护自身。',
		barPrefix: '今天',
		barPostfix: '{action}什么划算？',
		drawerAppearance: '外观',
		drawerTheme: '主题',
		drawerDay: '日间',
		drawerNight: '夜间',
		drawerAuto: '自动',
		drawerAutoUpdate: '即时更新',
		drawerQuality: '品质',
		drawerHQ: 'HQ',
		drawerNQ: 'NQ',
		drawerAll: '所有',
		drawerConsiderTime: '计算探险时间成本',
		drawerManualUpdate: '手动更新',
		drawerDC: '所在大区',
		drawerWorld: '所在服务器',
		drawerAverageWindowSize: '平均窗口大小',
		drawerUpdate: '更新',
		categoryCurrency: '货币',
		categoryRetainer: '雇员',
		categoryGathering: '采集',
		categoryCrafting: '生产',
		companySeal: '军票',
		companySealAction: "换",
		botany: '伐木',
		botanyAction: "砍",
		mining: '采矿',
		miningAction: '挖',
		fish: '捕鱼',
		fishAction: '钓',
		hunting: '战职',
		huntingAction: '带',
		dye: '染剂',
		dyeAction: '搓',
		map: '宝图',
		mapAaction: '挖',
		allegory: '奇谭',
		allegoryAction: '换',
		yellowGathererScrips: '黄票',
		yellowGathererScripsAction: '换',
		gridItem: '物品',
		gridLevel: '{0}级',
		gridUpdateAt: '更新于',
		gridUpdateLocalAt: '本服',
		gridUpdateGlobalAt: '全服',
		gridCost: '成本',
		gridDefaultLowest: '本服最低',
		gridDefaultMeanLow: '平均低价',
		gridDefaultHistLow: '成交均价',
		gridDefaultHistPerCost: '单位成本价',
		gridLowest: '全服最低价',
		gridMeanLow: '平均低价',
		gridHistLow: '成交均价',
		gridHistPerCost: '单位成本价',
		gridVolumes: '1/3/7日成交',
		gridItemName: '{name}',
		copyHint: '已拷贝至剪贴板'
	}
});



export default strings;