name: Auto Rebase Dependencies
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'dev-deps'
    tags:
      - 'dependencies'
jobs:
  do_rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "rebase"
          MERGE_LABELS: "dependencies"
          MERGE_ERROR_FAIL: 1