name: Auto Rebase Dependencies
permissions:
  contents: write
  issues: write
  discussions: write
  pull-requests: write
on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - 'dev-deps'
    tags:
      - 'dependencies'
jobs:
  do_rebase:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}